# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loadVars <- function(X, Y, V, D, nPredictors, cType = 1L, mSplit = 15L, mBucket = 10L, cp = 0.01) {
    .Call('fTree_loadVars', PACKAGE = 'fTree', X, Y, V, D, nPredictors, cType, mSplit, mBucket, cp)
}

unloadVars <- function() {
    invisible(.Call('fTree_unloadVars', PACKAGE = 'fTree'))
}

findOneBestContinuousSplit <- function(INDEX, pIndex) {
    .Call('fTree_findOneBestContinuousSplit', PACKAGE = 'fTree', INDEX, pIndex)
}

findOneBestCategoricalSplit <- function(INDEX, pIndex) {
    .Call('fTree_findOneBestCategoricalSplit', PACKAGE = 'fTree', INDEX, pIndex)
}

findAllBestSplits <- function(INDEX, currentGoodness) {
    .Call('fTree_findAllBestSplits', PACKAGE = 'fTree', INDEX, currentGoodness)
}

fTreeRPart <- function(INDEX, currentGoodness, depth) {
    .Call('fTree_fTreeRPart', PACKAGE = 'fTree', INDEX, currentGoodness, depth)
}

fTreeBootstrap <- function(BOOTINDEX) {
    .Call('fTree_fTreeBootstrap', PACKAGE = 'fTree', BOOTINDEX)
}

computeGoodness <- function(INDEX) {
    .Call('fTree_computeGoodness', PACKAGE = 'fTree', INDEX)
}

sseCost <- function(INDEX) {
    .Call('fTree_sseCost', PACKAGE = 'fTree', INDEX)
}

mahalanobisCost <- function(INDEX) {
    .Call('fTree_mahalanobisCost', PACKAGE = 'fTree', INDEX)
}

l2Cost <- function(INDEX) {
    .Call('fTree_l2Cost', PACKAGE = 'fTree', INDEX)
}

wssCost <- function(INDEX) {
    .Call('fTree_wssCost', PACKAGE = 'fTree', INDEX)
}

rdsCost <- function(INDEX) {
    .Call('fTree_rdsCost', PACKAGE = 'fTree', INDEX)
}

getAllCombinations <- function(N) {
    .Call('fTree_getAllCombinations', PACKAGE = 'fTree', N)
}

combToString <- function(combination) {
    .Call('fTree_combToString', PACKAGE = 'fTree', combination)
}

getCombinIndices <- function(Xcov, Combination, lr) {
    .Call('fTree_getCombinIndices', PACKAGE = 'fTree', Xcov, Combination, lr)
}

