# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loadVars <- function(X, covarType, Y, V, D, nPredictors, cType = 1L, mSplit = 15L, mBucket = 10L, cp = 0.01, argStep = 1) {
    .Call('_fTree_loadVars', PACKAGE = 'fTree', X, covarType, Y, V, D, nPredictors, cType, mSplit, mBucket, cp, argStep)
}

unloadVars <- function() {
    invisible(.Call('_fTree_unloadVars', PACKAGE = 'fTree'))
}

findOneBestContinuousSplit <- function(INDEX, pIndex) {
    .Call('_fTree_findOneBestContinuousSplit', PACKAGE = 'fTree', INDEX, pIndex)
}

findOneBestCategoricalSplit <- function(INDEX, pIndex) {
    .Call('_fTree_findOneBestCategoricalSplit', PACKAGE = 'fTree', INDEX, pIndex)
}

findAllBestSplits <- function(INDEX, currentGoodness) {
    .Call('_fTree_findAllBestSplits', PACKAGE = 'fTree', INDEX, currentGoodness)
}

fTreeRPart <- function(INDEX, currentGoodness, depth) {
    .Call('_fTree_fTreeRPart', PACKAGE = 'fTree', INDEX, currentGoodness, depth)
}

fTreeBootstrap <- function(BOOTINDEX) {
    .Call('_fTree_fTreeBootstrap', PACKAGE = 'fTree', BOOTINDEX)
}

computeGoodness <- function(INDEX) {
    .Call('_fTree_computeGoodness', PACKAGE = 'fTree', INDEX)
}

sseCost <- function(INDEX) {
    .Call('_fTree_sseCost', PACKAGE = 'fTree', INDEX)
}

mahalanobisCost <- function(INDEX) {
    .Call('_fTree_mahalanobisCost', PACKAGE = 'fTree', INDEX)
}

l2Cost <- function(INDEX) {
    .Call('_fTree_l2Cost', PACKAGE = 'fTree', INDEX)
}

wssCost <- function(INDEX) {
    .Call('_fTree_wssCost', PACKAGE = 'fTree', INDEX)
}

sql2Cost <- function(INDEX) {
    .Call('_fTree_sql2Cost', PACKAGE = 'fTree', INDEX)
}

rdsCost <- function(INDEX) {
    .Call('_fTree_rdsCost', PACKAGE = 'fTree', INDEX)
}

getAllCombinations <- function(N) {
    .Call('_fTree_getAllCombinations', PACKAGE = 'fTree', N)
}

combToString <- function(combination, categories) {
    .Call('_fTree_combToString', PACKAGE = 'fTree', combination, categories)
}

getCombinIndices <- function(Xcov, Combination, categories) {
    .Call('_fTree_getCombinIndices', PACKAGE = 'fTree', Xcov, Combination, categories)
}

